language: objective-c
osx_image: xcode9.2

env:
  - ACTION='build test'  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION='build test'  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 8'
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm'
  - ACTION='build test'  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV'

script:
  - xcodebuild clean $ACTION -project HyperSpace.xcodeproj -scheme HyperSpace-Package -destination "$DESTINATION"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
