# safelist
branches:
  only:
  - master

language: generic

env:
  global:
    - PROJECT=HyperSpace

matrix:
  include:
    - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=macOS'   }
    - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=iOS'     }
    - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=watchOS' }
    - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=tvOS'    }
    - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=SwiftPM' }
    - { os: linux, language: generic,       dist: trusty,          env:  'DEPMGT=SwiftPM SWIFT_VERSION=4.0', sudo: required }
    # - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=macOS     DESTINATION="platform=OS X"' }
    # - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=iOS       DESTINATION="platform=iOS Simulator,name=iPhone 8"' }
    # - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=watchOS   DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm"'}
    # - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=Carthage   PLATFORM=tvOS      DESTINATION="platform=tvOS Simulator,name=Apple TV"' }
    # - { os: osx,   language: objective-c,   osx_image: xcode9.2,   env: 'DEPMGT=SwiftPM' }
    # - { os: linux,    dist: trusty,   sudo: required,   language: generic,    env:  'DEPMGT=SwiftPM SWIFT_VERSION=4.0'}

before_install:
  - case $DEPMGT in
    Carthage)
      brew update;
      brew outdated carthage || brew upgrade carthage;
      brew tap xcodeswift/sake git@github.com:xcodeswift/sake.git;
      brew install sake;;
    SwiftPM)
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
      fi;
      swift package --enable-prefetching update;;
    *)
      ;;
    esac;

script:
  - case $DEPMGT in
    Carthage)
      sake task carthage-build-platform-dependencies;
      sake task xcode-build-platform;
      sake task xcode-test-platform;;
    SwiftPM)
      swift test;;
    *)
      ;;
    esac;

after_success:
  - case $DEPMGT in
    Carthage)
      bash <(curl -s https://codecov.io/bash);;
    *)
      ;;
    esac;

notifications:
  email: true
